const {chromium}=require('playwright');const fs=require('fs');const path=require('path');const assert=require('assert/strict');const crypto=require('crypto');
const root=process.cwd(),base='https://salvapicconi.github.io/conoscenzessas2025/',out=fs.mkdtempSync(require('os').tmpdir()+'/ssas-rilascio-');fs.mkdirSync(out,{recursive:true});
const report={checks:[]};const save=()=>fs.writeFileSync(out+'/esito.json',JSON.stringify(report,null,2));save();
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const contexts=[];async function context(){const c=await b.newContext({viewport:{width:1280,height:950}});contexts.push(c);await c.route(base+'**',async r=>{const rel=decodeURIComponent(new URL(r.request().url()).pathname.slice('/conoscenzessas2025/'.length))||'index.html';const f=path.resolve(root,rel);if(!f.startsWith(root+path.sep))return r.abort();try{await r.fulfill({path:f})}catch{await r.fulfill({status:404,body:'not found'})}});return c;}
 const c=await context(),p=await c.newPage();p.on('dialog',d=>d.accept());const errors=[];p.on('pageerror',e=>errors.push(e.message));
 // Coordinator plan, origins and cross-year restored state.
 await p.goto(base+'piano-uda.html');await p.waitForFunction(()=>stato.pronto);assert.equal(await p.evaluate(()=>stato.catalogo.size),102);await p.locator('[data-campo=anno]').selectOption('2');await p.locator('#piano-uda-U1-1').check();await p.locator('[data-campo=anno]').selectOption('1');await p.locator('#piano-uda-1-1').click();assert.equal(await p.locator('#piano-uda-1-1').isChecked(),false);await p.locator('[data-campo=anno]').selectOption('2');await p.locator('#piano-uda-U2-3a').check();await p.locator('#piano-uda-U2-3b').check();await p.reload();await p.waitForFunction(()=>stato.pronto);assert.equal(await p.evaluate(()=>stato.scelte.size),3);
 const planData=await p.evaluate(()=>JSON.stringify(costruisciPiano(scelteOrdinate())));assert.ok(planData.includes('C7'));assert.ok(planData.includes('Bozza'));assert.equal(await p.locator('#piano-import').isVisible(),false);
 const planDownload=await Promise.all([p.waitForEvent('download'),p.locator('[data-azione=word]').first().click()]);await planDownload[0].saveAs(out+'/piano.docx');report.checks.push('Piano coordinatore: 102 schede, unificate, doppio conteggio bloccato, persistenza, Word');save();
 await p.goto(base+'area-indirizzo.html');await p.waitForFunction(()=>typeof allData!=='undefined'&&allData.length>0);let dl=await Promise.all([p.waitForEvent('download'),p.evaluate(()=>exportExcel())]);await dl[0].saveAs(out+'/curricolo.xlsx');dl=await Promise.all([p.waitForEvent('download'),p.evaluate(()=>exportWord())]);await dl[0].saveAs(out+'/curricolo.docx');report.checks.push('Area indirizzo: esportazioni DOCX e XLSX');save();
 await p.goto(base+'uda.html');await p.waitForSelector('.uda-stampa',{state:'attached'});await p.locator('.uda-acc-header').first().click();dl=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'📄 Scarica in Word',exact:true}).first().click()]);await dl[0].saveAs(out+'/uda.docx');
 await p.goto(base+'uda-unificate.html');await p.waitForSelector('.uda-acc');assert.equal(await p.locator('.uda-acc').count(),36);assert.equal(await p.locator('.uda-nuova').count(),9);assert.equal(await p.locator('#uda-revisione-apri-accesso').isVisible(),true);assert.equal(await p.locator('[data-uda-revisione-key]').count(),27);assert.equal(await p.locator('[data-uda-revisione-slot]').count(),27);await c.route('**/functions/v1/curricolo-uda-revisioni',async r=>{const a=r.request().postDataJSON()?.action;await r.fulfill({status:200,contentType:'application/json',headers:{'Access-Control-Allow-Origin':'https://salvapicconi.github.io','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-curricolo-session','Access-Control-Allow-Methods':'POST, OPTIONS'},body:JSON.stringify(a==='login'?{ok:true,token:'x'.repeat(40),author_name:'Prof. Picconi',permissions:{manage_status:true}}:a==='list'?{revisions:[]}:{ok:true,author_name:'Prof. Picconi',permissions:{manage_status:true}})})});await p.locator('#uda-revisione-apri-accesso').click();await p.locator('#uda-revisione-docente').selectOption({label:'Prof. Picconi'});await p.locator('#uda-revisione-password').fill('verifica-locale');await p.locator('.uda-revisione-auth button[type=submit]').click();await p.locator('.uda-acc-header').first().click();await p.locator('.uda-revisione-card-actions button').first().waitFor();assert.equal(await p.locator('.uda-revisione-card-actions button').count(),27);await p.locator('.uda-revisione-card-actions button').first().click();assert.equal(await p.locator('.uda-revisione-editor').count(),1);report.checks.push('UDA unificate: 27 schede modificabili + 9 nuove etichettate; apertura editor verificata');save();
 await p.goto(base+'index.html#piano');assert.equal(await p.locator('.tab-button').count(),12);assert.equal(await p.locator('[data-tab=uda]').count(),0);assert.equal(await p.locator('[data-tab=votazione]').count(),0);assert.equal(await p.locator('[data-tab=esame]').count(),1);assert.equal(await p.locator('[data-tab=didattica]').count(),1);assert.equal(await p.locator('[data-tab=normativa]').count(),1);await p.setViewportSize({width:390,height:844});await p.screenshot({path:out+'/mobile.png',fullPage:false});
 await p.goto(base+'normativa.html');await p.waitForSelector('.norma-voce');assert.equal(await p.locator('.norma-voce').count(),29);assert.equal(await p.locator('.norma-fonte').count(),12);assert.equal(await p.locator('.norma-fonte a[href^="https://"]').count(),24);await p.locator('#norma-ricerca').fill('prova esperta');assert.equal(await p.locator('.norma-voce:visible').count(),1);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false);await p.goto(base+'index.html#normativa');assert.equal(await p.locator('[data-tab=normativa][aria-selected=true]').count(),1);const normFrame=await(await p.waitForSelector('#content-normativa iframe')).contentFrame();await normFrame.waitForSelector('.norma-voce');assert.equal(await normFrame.locator('.norma-voce').count(),29);report.checks.push('Riferimenti normativi: 29 termini, 12 fonti istituzionali, ricerca, collegamento dalla home e mobile senza overflow');save();
 await p.goto(base+'votazione-uda.html');assert.equal(await p.locator('form').count(),0);assert.equal(await p.locator('script[src*="votazione-uda.js"]').count(),0);assert.ok((await p.locator('h1').textContent()).includes('non disponibile'));assert.deepEqual(errors,[]);report.checks.push('Navigazione e voto oscurato; nessun errore JavaScript');delete report.error;report.success=true;save();console.log(JSON.stringify(report));
 // Nessuna chiamata di scrittura al backend in questo controllo.

 }finally{await b.close()}})().catch(e=>{report.error=e.message;save();console.error(e);process.exit(1)});
