const {chromium}=require('playwright');const fs=require('fs');const path=require('path');const assert=require('assert/strict');const crypto=require('crypto');
const root=process.cwd(),base='https://salvapicconi.github.io/conoscenzessas2025/',out=fs.mkdtempSync(require('os').tmpdir()+'/ssas-rilascio-');fs.mkdirSync(out,{recursive:true});
const report={checks:[]};const save=()=>fs.writeFileSync(out+'/esito.json',JSON.stringify(report,null,2));save();
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const contexts=[];async function context(){const c=await b.newContext({viewport:{width:1280,height:950}});contexts.push(c);await c.route(base+'**',async r=>{const rel=decodeURIComponent(new URL(r.request().url()).pathname.slice('/conoscenzessas2025/'.length))||'index.html';const f=path.resolve(root,rel);if(!f.startsWith(root+path.sep))return r.abort();try{await r.fulfill({path:f})}catch{await r.fulfill({status:404,body:'not found'})}});return c;}
 const c=await context(),p=await c.newPage();p.on('dialog',d=>d.accept());const errors=[];p.on('pageerror',e=>errors.push(e.message));
 // Coordinator plan, origins and cross-year restored state.
 await p.goto(base+'piano-uda.html');await p.waitForFunction(()=>stato.pronto);assert.equal(await p.evaluate(()=>stato.catalogo.size),93);await p.locator('[data-campo=anno]').selectOption('2');await p.locator('#piano-uda-U1-1').check();await p.locator('[data-campo=anno]').selectOption('1');await p.locator('#piano-uda-1-1').click();assert.equal(await p.locator('#piano-uda-1-1').isChecked(),false);await p.locator('[data-campo=anno]').selectOption('2');await p.locator('#piano-uda-U2-3a').check();await p.locator('#piano-uda-U2-3b').check();await p.reload();await p.waitForFunction(()=>stato.pronto);assert.equal(await p.evaluate(()=>stato.scelte.size),3);
 const planData=await p.evaluate(()=>JSON.stringify(costruisciPiano(scelteOrdinate())));assert.ok(planData.includes('C7'));assert.ok(planData.includes('Bozza'));assert.equal(await p.locator('#piano-import').isVisible(),false);
 const planDownload=await Promise.all([p.waitForEvent('download'),p.locator('[data-azione=word]').first().click()]);await planDownload[0].saveAs(out+'/piano.docx');report.checks.push('Piano coordinatore: 93 schede, unificate, doppio conteggio bloccato, persistenza, Word');save();
 await p.goto(base+'area-indirizzo.html');await p.waitForFunction(()=>typeof allData!=='undefined'&&allData.length>0);let dl=await Promise.all([p.waitForEvent('download'),p.evaluate(()=>exportExcel())]);await dl[0].saveAs(out+'/curricolo.xlsx');dl=await Promise.all([p.waitForEvent('download'),p.evaluate(()=>exportWord())]);await dl[0].saveAs(out+'/curricolo.docx');report.checks.push('Area indirizzo: esportazioni DOCX e XLSX');save();
 await p.goto(base+'uda.html');await p.waitForSelector('.uda-stampa',{state:'attached'});await p.locator('.uda-acc-header').first().click();dl=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'📄 Scarica in Word',exact:true}).first().click()]);await dl[0].saveAs(out+'/uda.docx');
 await p.goto(base+'index.html#piano');assert.equal(await p.locator('.tab-button').count(),9);assert.equal(await p.locator('[data-tab=uda]').count(),0);assert.equal(await p.locator('[data-tab=votazione]').count(),0);await p.setViewportSize({width:390,height:844});await p.screenshot({path:out+'/mobile.png',fullPage:false});
 await p.goto(base+'votazione-uda.html');assert.equal(await p.locator('form').count(),0);assert.equal(await p.locator('script[src*="votazione-uda.js"]').count(),0);assert.ok((await p.locator('h1').textContent()).includes('non disponibile'));assert.deepEqual(errors,[]);report.checks.push('Navigazione e voto oscurato; nessun errore JavaScript');delete report.error;report.success=true;save();console.log(JSON.stringify(report));
 // Nessuna chiamata di scrittura al backend in questo controllo.

 }finally{await b.close()}})().catch(e=>{report.error=e.message;save();console.error(e);process.exit(1)});
